version: "3"
services:

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/html
    ports:
      - "81:80"
    links:
      - php:php

  php:
    build: ./php
    expose:
      - "9000"
    links:
      - redis
    volumes:
      - ./web:/var/www/html

  redis:
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - ./redis:/data
